-- AOG shared schema (no secrets). Run once on the project.

create table if not exists public.packets (
  id bigint generated by default as identity primary key,
  station_id text not null default 'AOG-DEMO-1',
  n bigint,
  t double precision,
  gps integer,
  lat double precision,
  lon double precision,
  mq9 integer,
  a8 integer,
  a9 integer,
  v double precision,
  a_h double precision,
  created_at timestamptz not null default now()
);

create index if not exists packets_created_at_idx on public.packets (created_at desc);
create index if not exists packets_station_idx on public.packets (station_id, created_at desc);

alter table public.packets enable row level security;

revoke insert, update, delete on public.packets from anon, authenticated;
grant select on public.packets to anon, authenticated;

drop policy if exists demo_public_read on public.packets;
create policy demo_public_read
  on public.packets
  for select
  to anon, authenticated
  using (station_id = 'AOG-DEMO-1');

drop policy if exists demo_anon_insert on public.packets;
drop policy if exists packets_anon_delete_old on public.packets;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'packets'
  ) then
    execute 'alter publication supabase_realtime add table public.packets';
  end if;
end $$;

NOTIFY pgrst, 'reload schema';
