const CALENDAR_TR =
  "Kurulumdan sonra ilk iki ay sabit karar kullanılır. İkinci aydan sonra dinamik karar algoritması devreye girer. Altıncı aydan sonra makine öğrenmesi kararlara katılır; sekizinci aya kadar payı artar. On ikinci ayda sabit karar ve dinamik algoritma kapanır, öğrenme sistemi tek başına kalır.";

const CALENDAR_EN =
  "For the first two months after install the box uses a fixed decision. After month two a dynamic decision algorithm starts. After month six machine learning starts to affect the decision; its share grows until month eight. At month twelve the fixed decision and the dynamic algorithm stop, and learning runs the system alone.";

export const COPY = {
  tr: {
    nav: {
      urun: "Ürün",
      izle: "İzleme",
      kutu: "Donanım",
      ana: "Ana",
      moduller: "Modüller",
      sistem: "Sistem",
      karisim: "Karışım",
      analizler: "Analizler",
      pano: "Pano",
      asistan: "Asistan",
      asistanAria: "Yapay zeka asistan",
      eklenti: "Eklenti",
      ogrenme: "Öğrenme",
      cihaz: "Cihaz",
      destek: "Destek",
      sayfalar: "Sayfalar",
      menu: "Menü",
      kapat: "Kapat",
      anaSayfa: "Ana sayfa",
      siteMenu: "Site menüsü",
      yasal: "Yasal",
      digerMetinler: "Diğer metinler",
      skip: "İçeriğe atla",
      brand: "Akıllı Orman Gözlemcisi ana sayfası",
      yazilim: "Yazılım",
      lang: "EN",
      langAria: "English",
    },
    specs: [
      { href: "/moduller#govde", label: "IP-67 Alüminyum kutu" },
      { href: "/moduller#max6675", label: "MAX6675 sıcaklık" },
      { href: "/moduller#gps", label: "NEO GPS" },
      { href: "/moduller#mq9", label: "MQ-9 gaz" },
      { href: "/moduller#flame", label: "Kızılötesi alev" },
      { href: "/moduller#lora", label: "Ra-02 LoRa" },
    ],
    chrome: {
      giris: "Giriş",
      kayit: "Kayıt",
      hesap: "Hesap",
      sayfaAciliyor: "Sayfa açılıyor.",
      panoAciliyor: "Pano açılıyor.",
      hesapOkunuyor: "Hesap okunuyor.",
    },
    home: {
      slogan: "Kül Olmaya Mahkum Değil, AOG ile Korumaya Alınmış Yeşil Bir Gelecek!",
      lede:
        "LoRa ile ormanı izleyen kutu ve gövdeye sürülen doğal kaplama aynı üründür. Pano sıcaklık, gaz, kızılötesi ve konumu son 24 saatte gösterir.",
      sisteme: "Sistemi incele",
      chipLora: "LoRa izleme",
      chipLoraBody: "Kutu ormanı eve bağlar. Paket Ra-02 433 MHz ile alıcıya çıkar.",
      chipAlarm: "Karar takvimi",
      chipAlarmBody: "Güneş ısısı yangın sayılmaz. Karar kurulum ayına göre değişir. Asistan alarm açmaz.",
      chipCoat: "Pasif kaplama",
      chipCoatBody: "Alevin yüzeye oturmasını yavaşlatır. Ekip yetişecek zamanı kazanır.",
      panoTicks: [
        "Telefonundan ormanı görürsün: sıcaklık, gaz, kızılötesi, konum.",
        "Kutuya Wi-Fi gerekmez. Paket LoRa ile çıkar.",
        "Kaplama alevi yavaşlatır. Ekip yetişecek zamanı kazanır.",
        "Son 24 saat elde durur. Sahaya gitmeden bakılır.",
      ],
      gainBox: "IP-67 gövde",
      gainBoxBody: "Alüminyum kutu, conta yuvası ve kablo rakoru hazır gelir. Güneş paneli bu kabuğa oturur.",
      gainFour: "Dört ölçüm",
      gainFourBody: "MAX6675, NEO GPS, MQ-9 (A3) ve iki kızılötesi göz (D8/D9) aynı döngüde bakılır.",
      gainAlert: "Karar takvimi",
      calendar: CALENDAR_TR,
      gainRadio: "LoRa 433 MHz",
      gainRadioBody: "Orman kutusu Wi-Fi taşımaz. Paket Ra-02 ile alıcıya çıkar.",
      banner:
        "AOG, LoRa ile ormanı izleyen kutu ve gövdeye sürülen doğal kaplamayı aynı satışta tutar.",
      asistan: "Asistan",
      modsTitle: "Modüller",
      modsLede:
        "Kutuda MAX6675, NEO GPS, MQ-9, iki kızılötesi göz ve Ra-02 LoRa vardır. Orman düğümü Wi-Fi taşımaz. Satılan ürün Akıllı Orman Gözlemcisi'dir.",
      modsList: "Parça listesi",
      modsBanner: "Altı modül tek kutudadır. Paket LoRa ile alıcıya, oradan panoya gider.",
      modsGo: "Modüllere git",
      flowGo: "Veri akışını gör",
      panoGo: "Panoyu aç",
      gutsAlt: "Açık orman kutusu. Kartlar turuncu conta yuvasının içinde.",
      fieldAlt: "Güneş panelli orman kutusu ve gövdeye sürülmüş kaplama bandı.",
      phoneAlt: "Pano telefon görünümü.",
      gutsTitle: "Güneş panelli gövde",
      panoPair: "Pano ve donanım",
      next: "Sonraki adım",
      hwBadge: "Donanım",
    },
    sistem: {
      badge: "Aktif izleme",
      h1: "Ölçümden uyarıya",
      lede:
        "Kutu ormanda ölçer, paket LoRa ile alıcıya çıkar, pano son 24 saati gösterir. Orman kutusu internete bağlı değildir; alıcı bağlıdır.",
      chain: [
        "Sensör ölçümü",
        "Veri toplama",
        "LoRa 433 MHz",
        "Paket kaydı",
        "Karar takvimi",
        "Pano ve ntfy",
      ],
      gainWifi: "Ormanda Wi-Fi yok",
      gainWifiBody: "Düğümde Wi-Fi yoktur. Paket Ra-02 LoRa 433 MHz ile alıcıya çıkar.",
      gainFour: "Dört ölçüm bir döngü",
      gainFourBody: "MAX6675, NEO GPS, MQ-9 (A3) ve iki kızılötesi göz (D8/D9) birlikte bakılır.",
      gainAlert: "Karar takvimi",
      gainDay: "Son 24 saat",
      gainDayBody: "Pano 24 saat tutar. Yeni paket eski özeti ezer. Eski satırlar listeden düşer.",
      flowTitle: "İşleyiş şeması",
      flowAlt: "AOG sistemi işleyiş akış şeması: sensör, Deneyap Kart, LoRa, paket kaydı, ntfy, mobil ve web.",
      flowCap: "AOG sistemi işleyiş akış şeması. Adımlar 1-6'dır; ardından sürekli güncelleme gelir.",
      how: "Nasıl çalışır?",
      step1: "Sensör ölçümü",
      step1Body:
        "Orman düğümü sıcaklığı MAX6675 ile okur. GPS, MQ-9 gaz ve iki kızılötesi göz (D8/D9) aynı döngüde bakılır. Düğümde Wi-Fi yoktur.",
      step2: "Veri toplama",
      step2Body:
        "Deneyap Kart 1A v2 şu alanları paketler: n, t, gps, lat, lon, mq9, a8, a9. Kızılötesi, a8 veya a9 sıfır olduğunda yanar (pull-up; boşta 1).",
      step3: "Veri iletimi",
      step3Body:
        "Ra-02 LoRa 433 MHz paketi alıcıya yollar. Gönderici MAC: f4:12:fa:de:f3:c. Alıcı internete bağlıdır; orman kutusu bağlı değildir.",
      step4: "Paket kaydı",
      step4Body: "Alıcı satırı paket tablosuna yazar. İstasyon kodu: AOG-DEMO-1. Pano son 24 saati çeker.",
      step5: "Analiz ve karar",
      step5Body: CALENDAR_TR,
      step6: "Bildirim",
      step6Body:
        "Web panosu yeni pakette yenilenir. ntfy konusu ekibe düşer. Iphone ve Android aynı siteyi PWA olarak ana ekrana alır.",
      close:
        "Sistem paketi gönderir, pano 24 saat tutar. Asistan aynı sitededir; alarm açmaz. Alevi geciktiren gövdedeki kaplamadır.",
      next: "Karışımı oku",
    },
    lookout: {
      h1: "Pano",
      loading: "Paket okunuyor.",
      silent: "Son 24 saatte paket gelmedi. Kutunun açık olduğunu kontrol et.",
      scoreLow: "Skor 0,5 altında.",
      calendarHit: "Takvim kararı.",
      mlHit: "Skor ≥ 0,5.",
      fixedHit: "Sabit karar.",
      irOnly: "Kızılötesi gördü; karar yok.",
      quiet: "Alarm yok.",
      calendarTitle: "Takvim kararı",
      mlTitle: "Öğrenme kararı",
      fixedTitle: "Sabit karar",
      retry: "Yeniden dene",
      sensors: "Sensörler",
      temp: "Sıcaklık",
      gas: "MQ-9",
      ir: "Kızılötesi",
      flame: "Alev",
      gps: "GPS",
      reading: "Okunuyor",
      notice: "Bildirim",
      tempLine: "Sıcaklık grafiği",
      map: "Harita",
      mapLoad: "Harita yükleniyor.",
      last: "Son uyarılar",
      empty: "Liste boş.",
      coat: "Kaplama durumu",
      coatRenew: "Karışım yenilendi",
      coatMeter: "Kaplama kalan ömrü",
      coatNew: "Yeni kaplama",
      coatMid: "Orta süre",
      coatNeed: "Yenileme gerekli",
      fail: "Paketler okunamadı.",
      rssiWait: "Paket bekleniyor",
      rssiRx: "Alıcı LoRa",
      hopDirect: "Doğrudan",
      d89: "D8 ve D9",
      loc: "Konum",
      tempLoad: "Sıcaklık paketleri okunuyor.",
      tempEmpty: "Son 24 saatte sıcaklık paketi yok.",
    },
    makine: {
      h1: "Makine öğrenmesi",
      ayar: "Ayar",
      eklenti: "Eklenti",
      kapat: "Kapat",
      ac: "Aç",
      alarm: "Alarm",
      sabit: "Sabit",
      takvim: "Takvim",
      yalniz: "Yalnız skor",
      kurulu: "Kurulu gün",
      kaydet: "Kaydet",
      skor: "Skor",
      bekliyor: "bekliyor",
      egitildi: "eğitildi",
      yok: "yok",
      kaydedildi: "Kaydedildi.",
      kapandi: "Kapandı.",
      acildi: "Açıldı.",
      pano: "Panoyu aç",
      how: CALENDAR_TR,
    },
    auth: {
      clerkOff: "Oturum için Clerk yayın anahtarı gerekir. Anahtar yazılmadan bu sayfa açılmaz.",
      panoLead: "Pano hesaba bağlıdır. Giriş yapmadan istasyon ekranı açılmaz.",
      asistanLead: "Sohbetler hesaba yazılır. Başka hesabın sohbeti bu tarayıcıda görünmez.",
      cihazLead: "Kutu ve cihaz sayfası hesaba bağlıdır. Giriş yapmadan cihaz ekranı açılmaz.",
    },
    cookie: {
      title: "Çerez ve yurt dışı aktarım",
      body:
        "Zorunlu çerezler hesap ve sohbet içindir. Yazı tipi (Google) ve harita karosu (OpenStreetMap) için 6698 / BTK açık rızası gerekir. Tercihi Çerezler sayfasından değiştirirsin.",
      optional: "İsteğe bağlı",
      fonts: "Yazı tipleri",
      map: "Harita karoları",
      reject: "Reddet",
      save: "Kaydet",
      accept: "Kabul et",
    },
    destek: {
      p: [
        "Akıllı Orman Gözlemcisi (AOG), Defenders Of Green (DOG) takımının projesidir.",
        "Yazılım kar amacı gütmez. Bağış veya para kabul etmeyiz.",
        "Kaynak kodunun tamamı MIT lisansı ile açıktır.",
        "Destek için GitHub deposunu yıldızlayın.",
      ],
      thanks: "Teşekkürler.",
    },
    eklenti: {
      badge: "Yazılım",
      h1: "Eklentiler",
      acik: "Açık",
      kapali: "Kapalı",
      cikar: "Çıkar",
      asistanAc: "Asistanı aç",
      ayar: "Ayar sayfası",
      kaydedildi: "Kaydedildi.",
      eklendi: "Eklendi.",
      cikarildi: "Çıkarıldı.",
      notuYaz: "Notu yaz",
      ekle: "Ekle",
      macNote: "S3 MAC notu",
      macPlaceholder: "S3 MAC",
      plugins: {
        hop: {
          title: "Mesh sistemi",
          body: "ESP32-S3, 433 MHz AOG paketini bir kez hop=1 ile tekrarlar.",
        },
        pi: {
          title: "Asistan",
          body: "Sorular Asistan sayfasından gider. Asistan alarm yazmaz.",
        },
        ml: {
          title: "Makine öğrenmesi",
          body: "Karar takvimi Öğrenme sayfasındadır. İlk iki ay sabit karar kullanılır. İkinci aydan sonra dinamik algoritma, altıncı aydan sonra öğrenme kararlara katılır; sekizinci aya kadar payı artar. On ikinci ayda sabit karar ve dinamik algoritma kapanır.",
        },
      },
    },
    karisim: {
      badge: "Pasif koruma",
      h1: "Pasif kaplama",
      lede:
        "Karışım yangını söndürmez. AOG'nin pasif kaplaması doğal bir yangın geciktiricidir: alevin yüzeye oturmasını yavaşlatır, tahliye ve müdahale için süre kazandırır. Formülasyon TEKNOFEST 2026 sunumundaki sıfır atık tarifidir.",
      stage: "Kaplama bandı ve dört bileşen.",
      logAlt: "Çam gövdesinde açık renk pasif kaplama bandı.",
      partsTitle: "Karışım bileşenleri",
      howTitle: "Nasıl çalışır?",
      labTitle: "Laboratuvar bulguları (YTÜ)",
      labBody:
        "TGA-DSC ölçümünde ana yanma sıcaklığı kaplamasız ağaçta 399 °C, taze kaplamada 424 °C, 3,5 ay yaşlanmış kaplamada 438 °C bulunmuştur. Sunum, maksimum kütle kaybı hızının kabaca üç kat düştüğünü yazar. FTIR, yüzeyin örtüldüğünü ve yaşlanmayla etkinin kısmen zayıfladığını gösterir.",
      labLead: "Ham spektrumlar",
      labTail: "sayfasındadır.",
      labCap:
        "Analizler Yıldız Teknik Üniversitesi Merkezi Araştırma Laboratuvarı'nda gerçekleştirilmiştir.",
      banner: "Kaplama alevi geciktirir; sensörler haber verir. İkisi birlikte AOG'dir.",
      nextLabs: "Analizlere geç",
      nextBoard: "Panoyu aç",
      next: "Sonraki adım",
      parts: [
        {
          name: "Aloe vera jeli",
          short: "Aloe vera jeli",
          role: "Su tutar; yüzeyi ıslak ve yapışkan tutar.",
          mark: "aloe",
        },
        {
          name: "Pirinç kabuğu külü (ince ve kalın)",
          short: "Pirinç kabuğu külü",
          role: "Silisli iskelet sağlar. İnce toz boşluğu doldurur; kalın taneler kabuğu tutar.",
          mark: "ash",
        },
        {
          name: "Yumurta kabuğu tozu",
          short: "Yumurta kabuğu tozu",
          role: "Kalsiyum karbonattır. Isıda gaz çıkarır; char tabakasını destekler.",
          mark: "shell",
        },
        {
          name: "Ksantan gam",
          short: "Ksantan gam",
          role: "Karışımı ağaca yapıştırır. Yağmurda hemen akmaması içindir.",
          mark: "gum",
        },
      ],
      gains: [
        {
          title: "Doğal içerik",
          body: "Sıfır atık tarifidir. Kimyasal yangın geciktirici iddiası yoktur.",
          icon: "leaf",
        },
        {
          title: "Yüzeye tutunur",
          body: "Jel ve gam, kabuğu ağaca yapıştırır.",
          icon: "shield",
        },
        {
          title: "Yayılmayı yavaşlatır",
          body: "Amaç kesmek değil, alevin yüzeye oturmasını yavaşlatmaktır.",
          icon: "fire",
        },
        {
          title: "Zaman kazandırır",
          body: "Kazanılan süre tahliye ve müdahale içindir.",
          icon: "clock",
        },
      ],
      steps: [
        {
          title: "Uygulama",
          body: "Karışım gövdeye eşit sürülür.",
          icon: "brush",
        },
        {
          title: "Koruyucu tabaka",
          body: "Yapışkan koruyucu bir tabaka oluşur.",
          icon: "shield",
        },
        {
          title: "Alev temasını geciktirme",
          body: "Isı geçişini ve alevin yüzeye oturmasını yavaşlatır.",
          icon: "fire",
        },
        {
          title: "Müdahale süresi",
          body: "Tahliye ve müdahale için süre kazandırır.",
          icon: "clock",
        },
      ],
      temps: [
        { value: "399 °C", label: "Kaplamasız ağaç" },
        { value: "424 °C", label: "Taze kaplama" },
        { value: "438 °C", label: "3,5 ay yaşlanmış kaplama" },
      ],
    },
    analizler: {
      kicker: "ANALİZLER",
      navAria: "Analiz bölümleri",
      legend: "Numune açıklamaları",
      filterAria: "Numune filtresi",
      all: "Tüm grafikler",
      sample: "numune",
      overlay: "Üst üste göster",
      expand: "Grafikleri genişlet",
      zoomBtn: "grafiğini büyüt",
      zoomAria: "Büyütülmüş grafik",
      close: "Kapat",
      foot: "Tüm analizler Yıldız Teknik Üniversitesi Merkezi Araştırma Laboratuvarı'nda yapılmıştır.",
      sections: {
        ftir: { label: "FTIR", title: "FTIR analizi" },
        tga: { label: "TGA-DSC", title: "TGA-DSC analizi" },
        raporlar: { label: "Raporlar", title: "Raporlar" },
      },
      notes: {
        ftir: "Doğal içerikli yangın geciktirici kaplamamızın kimyasal yapısını FTIR analizi ile inceliyoruz.",
        tga: "Doğal içerikli yangın geciktirici kaplamamızın ısıl davranışını TGA ve DSC ile inceliyoruz.",
        raporlar: "Ham ölçüm tabloları Yıldız Teknik Üniversitesi Merkezi Araştırma Laboratuvarı çıktılarıdır.",
      },
      samples: {
        a: "Taze karışım",
        b: "Kaplamasız ağaç",
        c: "Yeni kaplanmış ağaç",
        d: "3 ay kaplanmış ağaç",
      },
    },
    asistan: {
      hizli: "Hızlı cevaplar",
      orta: "Orta cevaplar",
      derin: "Derin cevaplar",
    },
    device: {
      iphone: "Iphone",
      android: "Android",
      pano: "Panoyu aç",
      iosOk: "AOG bu Iphone'da ana ekrandan açıktır. Safari çubuğu yoktur.",
      iosHow: "Safari'de Paylaş'a bas; Ana Ekrana Ekle'yi seç. AOG ayrı bir uygulama gibi açılır.",
      ios1: "Safari ile bu sayfayı aç.",
      ios2: "Paylaş",
      ios3: "Ana Ekrana Ekle",
      andOk: "AOG bu telefonda yüklüdür. Chrome çubuğu yoktur.",
      andHow: "Chrome menüsünden Uygulamayı yükle veya Ana ekrana ekle'yi seç. AOG ayrı bir uygulama gibi açılır.",
      install: "Uygulamayı yükle",
      which: "Hangi cihaz?",
      iosHint: "Bu telefon Iphone. Safari ile ana ekrana alınır.",
      androidHint: "Bu telefon Android. Chrome ile ana ekrana alınır.",
      otherHint: "Iphone, Android veya tarayıcı. Ana ekrana ekle.",
      web: "Tarayıcıda aç",
    },
    legal: {
      gizlilik: "Gizlilik",
      cerezler: "Çerezler",
      eula: "EULA",
      dmca: "DMCA",
      erisim: "Erişilebilirlik",
      destek: "Destek",
    },
  },
  en: {
    nav: {
      urun: "Product",
      izle: "Watch",
      kutu: "Hardware",
      ana: "Home",
      moduller: "Modules",
      sistem: "System",
      karisim: "Coat",
      analizler: "Labs",
      pano: "Board",
      asistan: "Assistant",
      asistanAria: "AI assistant",
      eklenti: "Add-ons",
      ogrenme: "Learning",
      cihaz: "Device",
      destek: "Support",
      sayfalar: "Pages",
      menu: "Menu",
      kapat: "Close",
      anaSayfa: "Home",
      siteMenu: "Site menu",
      yasal: "Legal",
      digerMetinler: "Other notices",
      skip: "Skip to content",
      brand: "Akıllı Orman Gözlemcisi home",
      yazilim: "Software",
      lang: "TR",
      langAria: "Türkçe",
    },
    specs: [
      { href: "/moduller#govde", label: "IP-67 aluminium case" },
      { href: "/moduller#max6675", label: "MAX6675 temperature" },
      { href: "/moduller#gps", label: "NEO GPS" },
      { href: "/moduller#mq9", label: "MQ-9 gas" },
      { href: "/moduller#flame", label: "Infrared flame" },
      { href: "/moduller#lora", label: "Ra-02 LoRa" },
    ],
    chrome: {
      giris: "Sign in",
      kayit: "Sign up",
      hesap: "Account",
      sayfaAciliyor: "Loading page.",
      panoAciliyor: "Opening the board.",
      hesapOkunuyor: "Reading the account.",
    },
    home: {
      slogan: "Not doomed to ash. With AOG a green future stays under watch.",
      lede:
        "A LoRa watch box and a natural coat on the trunk ship as one product. The board shows temperature, gas, infrared and location for the last 24 hours.",
      sisteme: "See the system",
      chipLora: "LoRa watch",
      chipLoraBody: "The box links the forest to the house. The packet leaves on Ra-02 at 433 MHz.",
      chipAlarm: "Decision calendar",
      chipAlarmBody: "Sun heat is not a fire. The decision changes with months since install. The assistant does not raise alarms.",
      chipCoat: "Passive coat",
      chipCoatBody: "The coat slows flame sitting on the surface. Crews gain time.",
      panoTicks: [
        "You see the forest on the phone: temperature, gas, infrared, location.",
        "The box does not need Wi-Fi. The packet leaves on LoRa.",
        "The coat slows flame. Crews gain time.",
        "The last 24 hours stay on the board. You do not walk the stand.",
      ],
      gainBox: "IP-67 body",
      gainBoxBody: "Aluminium case, gasket seat and cable gland come ready. The solar panel sits on this shell.",
      gainFour: "Four readings",
      gainFourBody: "MAX6675, NEO GPS, MQ-9 (A3) and two infrared eyes (D8/D9) share one loop.",
      gainAlert: "Decision calendar",
      calendar: CALENDAR_EN,
      gainRadio: "LoRa 433 MHz",
      gainRadioBody: "The forest box does not carry Wi-Fi. The packet leaves on Ra-02.",
      banner:
        "AOG ships a LoRa watch box and a natural coat on the trunk as one sale.",
      asistan: "Assistant",
      modsTitle: "Modules",
      modsLede:
        "The box holds MAX6675, NEO GPS, MQ-9, two infrared eyes and Ra-02 LoRa. The forest node does not carry Wi-Fi. The product on sale is Akıllı Orman Gözlemcisi.",
      modsList: "Parts list",
      modsBanner: "Six modules sit in one box. The packet leaves on LoRa to the receiver, then to the board.",
      modsGo: "See the modules",
      flowGo: "See the data flow",
      panoGo: "Open the board",
      gutsAlt: "Open forest box. Boards sit in the orange gasket seat.",
      fieldAlt: "Forest box with a solar panel and a coat band on the trunk.",
      phoneAlt: "Board on a phone.",
      gutsTitle: "Solar body",
      panoPair: "Board and hardware",
      next: "Next step",
      hwBadge: "Hardware",
    },
    sistem: {
      badge: "Active watch",
      h1: "From reading to notice",
      lede:
        "The box reads in the forest, the packet leaves on LoRa, the board keeps 24 hours. The forest box is not on the internet; the receiver is.",
      chain: [
        "Sensor read",
        "Packing",
        "LoRa 433 MHz",
        "Packet store",
        "Decision calendar",
        "Board and ntfy",
      ],
      gainWifi: "No Wi-Fi in the stand",
      gainWifiBody: "The node has no Wi-Fi. The packet leaves on Ra-02 LoRa 433 MHz.",
      gainFour: "Four readings, one loop",
      gainFourBody: "MAX6675, NEO GPS, MQ-9 (A3) and two infrared eyes (D8/D9) run together.",
      gainAlert: "Decision calendar",
      gainDay: "Last 24 hours",
      gainDayBody: "The board keeps 24 hours. A new packet replaces the old summary. Old rows drop off.",
      flowTitle: "Flow",
      flowAlt: "AOG system flow: sensor, Deneyap board, LoRa, packet store, ntfy, phone and web.",
      flowCap: "AOG system flow. Steps 1-6, then a live loop.",
      how: "How it runs",
      step1: "Sensor read",
      step1Body:
        "The forest node reads temperature with MAX6675. GPS, MQ-9 gas and two infrared eyes (D8/D9) share the loop. The node has no Wi-Fi.",
      step2: "Packing",
      step2Body:
        "Deneyap Kart 1A v2 packs n, t, gps, lat, lon, mq9, a8, a9. Infrared is on when a8 or a9 is zero (pull-up; idle is 1).",
      step3: "Radio",
      step3Body:
        "Ra-02 LoRa 433 MHz sends the packet to the receiver. Sender MAC: f4:12:fa:de:f3:c. The receiver is on the internet; the forest box is not.",
      step4: "Packet store",
      step4Body: "The receiver writes the row to the packet table. Station id: AOG-DEMO-1. The board pulls the last 24 hours.",
      step5: "Decision",
      step5Body: CALENDAR_EN,
      step6: "Notice",
      step6Body:
        "The web board refreshes on a new packet. The ntfy topic reaches the crew. iPhone and Android add the same site as a PWA.",
      close:
        "The system sends packets; the board keeps 24 hours. The assistant lives on the same site and does not raise alarms. The coat on the trunk is what slows flame.",
      next: "Read the coat",
    },
    lookout: {
      h1: "Board",
      loading: "Reading packets.",
      silent: "No packet in 24 hours. Check that the box is on.",
      scoreLow: "Score below 0.5.",
      calendarHit: "Calendar decision.",
      mlHit: "Score ≥ 0.5.",
      fixedHit: "Fixed decision.",
      irOnly: "Infrared saw something; no decision.",
      quiet: "No alarm.",
      calendarTitle: "Calendar decision",
      mlTitle: "Learning decision",
      fixedTitle: "Fixed decision",
      retry: "Try again",
      sensors: "Sensors",
      temp: "Temperature",
      gas: "MQ-9",
      ir: "Infrared",
      flame: "Flame",
      gps: "GPS",
      reading: "Reading",
      notice: "Notice",
      tempLine: "Temperature chart",
      map: "Map",
      mapLoad: "Loading map.",
      last: "Latest notices",
      empty: "List is empty.",
      coat: "Coat status",
      coatRenew: "Coat renewed",
      coatMeter: "Coat remaining life",
      coatNew: "New coat",
      coatMid: "Mid life",
      coatNeed: "Renewal due",
      fail: "Packets could not be read.",
      rssiWait: "Waiting for a packet",
      rssiRx: "Receiver LoRa",
      hopDirect: "Direct",
      d89: "D8 and D9",
      loc: "Location",
      tempLoad: "Reading temperature packets.",
      tempEmpty: "No temperature packet in 24 hours.",
    },
    makine: {
      h1: "Machine learning",
      ayar: "Settings",
      eklenti: "Add-on",
      kapat: "Off",
      ac: "On",
      alarm: "Alarm",
      sabit: "Fixed",
      takvim: "Calendar",
      yalniz: "Score only",
      kurulu: "Install day",
      kaydet: "Save",
      skor: "Score",
      bekliyor: "waiting",
      egitildi: "fitted",
      yok: "none",
      kaydedildi: "Saved.",
      kapandi: "Off.",
      acildi: "On.",
      pano: "Open the board",
      how: CALENDAR_EN,
    },
    auth: {
      clerkOff: "Clerk publishable key is required. This page stays closed without it.",
      panoLead: "The board is tied to an account. Sign in to open the station.",
      asistanLead: "Chats are stored for this account. Another account's chat does not show in this browser.",
      cihazLead: "The device page is tied to an account. Sign in to open it.",
    },
    cookie: {
      title: "Cookies and transfers abroad",
      body:
        "Required cookies run the account and chat. Fonts (Google) and map tiles (OpenStreetMap) need explicit consent under 6698 / BTK. You change the choice on the Cookies page.",
      optional: "Optional",
      fonts: "Fonts",
      map: "Map tiles",
      reject: "Reject",
      save: "Save",
      accept: "Accept",
    },
    destek: {
      p: [
        "Akıllı Orman Gözlemcisi (AOG) is a Defenders Of Green (DOG) project.",
        "The software is not for profit. We do not take donations or money.",
        "The full source is under the MIT license.",
        "Support us by starring the GitHub repository.",
      ],
      thanks: "Thanks.",
    },
    eklenti: {
      badge: "Software",
      h1: "Add-ons",
      acik: "On",
      kapali: "Off",
      cikar: "Remove",
      asistanAc: "Open assistant",
      ayar: "Settings page",
      kaydedildi: "Saved.",
      eklendi: "Added.",
      cikarildi: "Removed.",
      notuYaz: "Save note",
      ekle: "Add",
      macNote: "S3 MAC note",
      macPlaceholder: "S3 MAC",
      plugins: {
        hop: {
          title: "Mesh system",
          body: "An ESP32-S3 repeats the 433 MHz AOG packet once with hop=1.",
        },
        pi: {
          title: "Assistant",
          body: "Questions go from the Assistant page. The assistant does not write alarms.",
        },
        ml: {
          title: "Machine learning",
          body: "The decision calendar is on the Learning page. For the first two months the box uses a fixed decision. After month two a dynamic algorithm starts. After month six learning joins the decision; its share grows until month eight. At month twelve the fixed decision and the dynamic algorithm stop.",
        },
      },
    },
    karisim: {
      badge: "Passive protection",
      h1: "Passive coat",
      lede:
        "The mix does not put a fire out. AOG's passive coat is a natural fire retardant: it slows flame sitting on the surface and leaves time for evacuation and response. The formula is the zero-waste recipe from the TEKNOFEST 2026 presentation.",
      stage: "Coat band and four ingredients.",
      logAlt: "A pale passive coat band on a pine trunk.",
      partsTitle: "Mix ingredients",
      howTitle: "How it works",
      labTitle: "Lab findings (YTU)",
      labBody:
        "TGA-DSC put the main burn temperature at 399 °C on uncoated wood, 424 °C on a fresh coat, and 438 °C after 3.5 months of aging. The presentation writes that peak mass-loss rate fell by about three times. FTIR shows the surface is covered, and that the effect weakens somewhat with age.",
      labLead: "Raw spectra are on the",
      labTail: "page.",
      labCap: "The analyses were run at Yildiz Technical University Central Research Laboratory.",
      banner: "The coat delays flame; the sensors send word. Together they are AOG.",
      nextLabs: "See the labs",
      nextBoard: "Open the board",
      next: "Next step",
      parts: [
        {
          name: "Aloe vera gel",
          short: "Aloe vera gel",
          role: "It holds water and keeps the surface wet and sticky.",
          mark: "aloe",
        },
        {
          name: "Rice husk ash (fine and coarse)",
          short: "Rice husk ash",
          role: "A silica skeleton. Fine powder fills gaps; coarse grains hold the crust.",
          mark: "ash",
        },
        {
          name: "Eggshell powder",
          short: "Eggshell powder",
          role: "Calcium carbonate. Heat drives off gas and supports the char layer.",
          mark: "shell",
        },
        {
          name: "Xanthan gum",
          short: "Xanthan gum",
          role: "It sticks the mix to the tree so rain does not wash it off at once.",
          mark: "gum",
        },
      ],
      gains: [
        {
          title: "Natural ingredients",
          body: "This is a zero-waste recipe. There is no chemical fire-retardant claim.",
          icon: "leaf",
        },
        {
          title: "Sticks to the surface",
          body: "Gel and gum glue the crust to the tree.",
          icon: "shield",
        },
        {
          title: "Slows spread",
          body: "The coat does not cut the fire. It slows flame sitting on the surface.",
          icon: "fire",
        },
        {
          title: "Buys time",
          body: "The extra time is for evacuation and response.",
          icon: "clock",
        },
      ],
      steps: [
        {
          title: "Application",
          body: "The mix is spread evenly on the trunk.",
          icon: "brush",
        },
        {
          title: "Protective layer",
          body: "A sticky protective layer forms.",
          icon: "shield",
        },
        {
          title: "Delaying flame contact",
          body: "It slows heat transfer and flame sitting on the surface.",
          icon: "fire",
        },
        {
          title: "Response time",
          body: "It leaves time for evacuation and response.",
          icon: "clock",
        },
      ],
      temps: [
        { value: "399 °C", label: "Uncoated wood" },
        { value: "424 °C", label: "Fresh coat" },
        { value: "438 °C", label: "Coat aged 3.5 months" },
      ],
    },
    analizler: {
      kicker: "LABS",
      navAria: "Lab sections",
      legend: "Sample notes",
      filterAria: "Sample filter",
      all: "All plots",
      sample: "sample",
      overlay: "Stack plots",
      expand: "Enlarge plots",
      zoomBtn: "enlarge plot",
      zoomAria: "Enlarged plot",
      close: "Close",
      foot: "All analyses were run at Yildiz Technical University Central Research Laboratory.",
      sections: {
        ftir: { label: "FTIR", title: "FTIR analysis" },
        tga: { label: "TGA-DSC", title: "TGA-DSC analysis" },
        raporlar: { label: "Reports", title: "Reports" },
      },
      notes: {
        ftir: "FTIR looks at the chemical structure of the natural fire-retardant coat.",
        tga: "TGA and DSC look at how the natural fire-retardant coat behaves under heat.",
        raporlar: "The raw tables are outputs from Yildiz Technical University Central Research Laboratory.",
      },
      samples: {
        a: "Fresh mix",
        b: "Uncoated wood",
        c: "Newly coated wood",
        d: "Wood coated 3 months",
      },
    },
    modules: {
      govde: {
        name: "IP-67 aluminium case",
        alt: "Brushed aluminium industrial case with a lid.",
        body: "IP-67 aluminium case. Screw spacing, gasket seat and cable gland come ready. The solar panel and antenna sit on this shell. The product on sale is Akıllı Orman Gözlemcisi.",
      },
      max6675: {
        name: "MAX6675",
        alt: "MAX6675 K-type thermocouple converter and a steel-probe cable.",
        body: "A K-type thermocouple reaches heats that a plastic temperature chip would not survive in a forest fire. MAX6675 converts the analog voltage to a number over SPI with cold-junction compensation. The packet's t= field comes from here.",
      },
      gps: {
        name: "GY-GPSV3-NEO",
        alt: "u-blox NEO GPS board and a ceramic patch antenna.",
        body: "The u-blox NEO talks UART to the Deneyap board. The ceramic patch antenna is weak under trees. With no fix the packet writes gps=0 and the map places no marker. When a fix arrives, lat and lon drop onto the board to five decimals. A backup coin cell shortens hot starts. First power-up in the forest can still be a cold start.",
      },
      mq9: {
        name: "MQ-9",
        alt: "MQ-9 carbon monoxide and flammable-gas sensor.",
        body: "MQ-9 is a semiconductor cage sensitive to carbon monoxide and flammable gases. Analog out goes to Deneyap pin A3. Packet mq9= is the raw ADC value; there is no ppm claim. The heater takes a few minutes to warm. A potentiometer sets the digital comparator. Software does not raise an alarm from gas.",
      },
      flame: {
        name: "Infrared flame",
        alt: "Infrared flame module, LM393 comparator and trimmer.",
        body: "The module sees infrared from flame with a phototransistor. The LM393 comparator goes digital. The box has two infrared eyes. The board does not show them as two products; it gives one infrared reading. The decision calendar is on the Learning page.",
      },
      lora: {
        name: "Ra-02 LoRa",
        alt: "Ai-Thinker Ra-02 LoRa breakout, U.FL antenna and headers.",
        body: "Ai-Thinker Ra-02 is an SX1278-based 410-525 MHz LoRa transceiver. PA output is +18 dBm. SPI (NSS, MOSI, MISO, SCK) and the DIO0 interrupt are wired to Deneyap. The forest box does not carry Wi-Fi. The packet leaves at 433 MHz. The antenna goes from U.FL. Shielded cable cuts noise in the stand.",
      },
    },
    asistan: {
      hizli: "Fast replies",
      orta: "Medium replies",
      derin: "Deep replies",
    },
    device: {
      iphone: "iPhone",
      android: "Android",
      pano: "Open the board",
      iosOk: "AOG is open from the home screen on this iPhone. There is no Safari chrome.",
      iosHow: "In Safari tap Share, then Add to Home Screen. AOG opens like an app.",
      ios1: "Open this page in Safari.",
      ios2: "Share",
      ios3: "Add to Home Screen",
      andOk: "AOG is installed on this phone. There is no Chrome chrome.",
      andHow: "In the Chrome menu pick Install app or Add to Home screen. AOG opens like an app.",
      install: "Install app",
      which: "Which device?",
      iosHint: "This phone is an iPhone. Add it from Safari.",
      androidHint: "This phone is Android. Add it from Chrome.",
      otherHint: "iPhone, Android or browser. Add it to the home screen.",
      web: "Open in the browser",
    },
    legal: {
      gizlilik: "Privacy",
      cerezler: "Cookies",
      eula: "EULA",
      dmca: "DMCA",
      erisim: "Accessibility",
      destek: "Support",
    },
  },
};
