-- Vanilla Postgres + PostgREST roles for AOG on the Pi.

create role authenticator noinherit login password 'aog_authenticator';
create role anon nologin;
create role authenticated nologin;
create role service_role nologin;
grant anon, authenticated, service_role to authenticator;

create table if not exists public.packets (
  id bigint generated by default as identity primary key,
  station_id text not null default 'AOG-DEMO-1',
  n bigint,
  t double precision,
  gps integer,
  lat double precision,
  lon double precision,
  mq9 integer,
  a8 integer,
  a9 integer,
  v double precision,
  a_h double precision,
  rssi integer,
  hop integer,
  created_at timestamptz not null default now()
);

create index if not exists packets_created_at_idx on public.packets (created_at desc);
create index if not exists packets_station_idx on public.packets (station_id, created_at desc);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  station_id text not null default 'AOG-DEMO-1',
  n bigint,
  score double precision not null,
  model text not null default 'logreg',
  created_at timestamptz not null default now()
);

create index if not exists scores_station_idx on public.scores (station_id, created_at desc);

grant usage on schema public to anon, authenticated, service_role;
grant select on public.packets, public.scores to anon, authenticated, service_role;
grant insert, update on public.packets, public.scores to service_role;
grant usage, select on all sequences in schema public to service_role;
